(*

#use "Text_editing/Text_lengthening/text_lengthener_standard.ml";;

*)

(* Description of standard text lengthener starts here *)


let one = 
{
 Text_lengthener_t.adjustable_decompressions=
[
    ("ait","ait",
[
                    ("expliqu","","expliquer");
]
    );
    ("aa","aire",
                  []
    );
    ("ax","eaux",
                  []
    );
    ("b","able",
[
                   ("considér","","consid");
                   ("indéstruct","ible","indéstruct");
                   ("imposs","ible","impss");
                   ("sens","ible","sens");
]
    );
    ("blt","bilité",
[
                        ("infailli","","ifll");
                        ("impecca","","ipcc");
                        ("possi","","poss");
]
    );
    ("e","e",
[
                ("ancienn","","ancien");
                ("chrétienn","","chrétien");
                ("publiqu","","public");
                ("surnaturell","","surnaturel");
]
    );
    ("é","é",
[
                  ("attaqu","","attaque");
                  ("authenticit","","auth");
                  ("invoqu","","invoque");
                  ("passionn","","passion");
]
    );
    ("ent","ent",
[
                    ("attaqu","","attaque");
                    ("exist","","existe");
                    ("invoqu","","invoque");
]
    );
    ("eur","eur",
                  []
    );
    ("f","f",
[
                ("autre","fois","autre");
                ("par","fois","par");
]
    );
    ("id","itude",
[
                     ("","idée","");
]
    );
    ("io","tion",
[
                    ("accusa","","accus");
                    ("appari","","appar");
                    ("aspira","","aspir");
                    ("conclu","sion","conclu");
                    ("condi","","cond");
                    ("considéra","","consid");
                    ("contradic","","contrad");
                    ("érudi","","érud");
                    ("imagina","","imagine");
                    ("propaga","","propag");
                    ("tradi","","trad");
]
    );
    ("ix","ieux",
[
                    ("sér","","sr");
]
    );
    ("î","ître",
                   []
    );
    ("í","ité",
                  []
    );
    ("ll","elle",
[
                    ("ai","lleurs","ai");
                    ("bat","aille","bat");
                    ("natur","","nature");
                    ("personn","","personne");
]
    );
    ("m","ment",
[
                   ("directe","","direct");
                   ("égale","","égal");
                   ("habile","","habil");
                   ("particulière","","particulier");
                   ("raisonne","","raison");
                   ("rapproche","","rapproch");
                   ("seule","","seul");
                   ("simple","","simpl");
]
    );
    ("mtt","mettre",
                     []
    );
    ("nc","nce",
[
                   ("différe","","différ");
                   ("éloque","","éloq");
                   ("importa","","import");
                   ("influe","","iflu");
                   ("intellige","","intellg");
                   ("obéissa","","obéiss");
                   ("préfére","","préfér");
                   ("provide","","provid");
]
    );
    ("nw","ctuel",
                   []
    );
    ("q","que",
[
                  ("atta","","at");
                  ("caractéristi","","caractère");
                  ("consé","quent","consé");
                  ("criti","","crt");
                  ("énergi","","énerg");
                  ("ecclésiasti","","ecc");
                  ("épo","","ép");
                  ("évangéli","","évangile");
                  ("expli","quer","xpl");
                  ("histori","","histoire");
                  ("invo","","iv");
                  ("inatta","qu","inat");
                  ("logi","","lg");
                  ("mythologi","","mytholg");
                  ("linguisti","","lingst");
                  ("liturgi","","liturg");
                  ("métaphysi","","métaphys");
                  ("par ce"," que","pc");
                  ("philosophi","","philosophie");
                  ("polémi","","polém");
                  ("pour","quoi","p");
                  ("quel","","q");
                  ("","question","");
                  ("scientifi","","science");
                  ("stratégi","","stratég");
                  ("théologi","","théol");
                  ("tragi","","trag");
]
    );
    ("s","s",
              []
    );
    ("ss","esse",
                  []
    );
    ("zn","isme",
[
                    ("catholic","","catholique");
                    ("christian","","chrétien");
                    ("sceptic","","scep");
]
    );
    ("-m^","-même",
                     []
    );
    ("-vs","-vous",
                    []
    );
];
expansions=
[
    ["ll";"nc"];
    ["ll";"nw"];
    ["-m^";"s"];
    ["q";"ent"];
    ["aa";"s"];
    ["ait"];
    ["blt"];
    ["é";"e";"s"];
    ["ent"];
    ["eur"];
    ["aa";"s"];
    ["id";"s"];
    ["io";"s"];
    ["ll";"s"];
    ["ss";"m"];
    ["-m^"];
    ["-vs"];
    ["aa"];
    ["ax"];
    ["b";"m"];
    ["b";"s"];
    ["é";"e"];
    ["e";"m"];
    ["e";"s"];
    ["id"];
    ["io"];
    ["ix"];
    ["ll"];
    ["m";"s"];
    ["nc"];
    ["q";"b"];
    ["q";"é"];
    ["q";"m"];
    ["q";"s"];
    ["zn"];
    ["b"];
    ["e"];
    ["f"];
    ["é"];
    ["î"];
    ["í"];
    ["m"];
    ["q"];
    ["s"];
];
inert_words=
[
    "donc";
    "idée";
    "je";
    "nom";
    "prix";
    "voix";
];
left_core_abbreviations=
[
    ("absolu","absl");
    ("abomin","abom");
    ("académie","acad");
    ("ainsi","asi");
    ("allemand","allmd");
    ("âme","â");
    ("amour","amr");
    ("ancien","anci");
    ("apocalypse","apoc");
    ("apocryphe","apocr");
    ("apôtre","apô");
    ("après","aft");
    ("aujourd'hui","auj");
    ("aveugle","avgl");
    ("beaucoup","bcp");
    ("caractère","khi");
    ("catholique","catho");
    ("c'est-à-dire","cad");
    ("cependant","ksk");
    ("c'est","di");
    ("ce n'est","din");
    ("chose","ch");
    ("cherche","chch");
    ("chercher","chchr");
    ("chrétien","chr");
    ("christianisme","chisme");
    ("collègue","collg");
    ("coup","cp");
    ("conférence","confé");
    ("contradiction","contradio");
    ("controverse","controv");
    ("croyant","croy");
    ("de","de");
    ("démonstration","démo");
    ("démontrer","démor");
    ("divinité","div");
    ("divinité du Christ","ddC");
    ("dogme","dgm");
    ("dogme de la divinité du Christ","dddC");
    ("Dieu","D");
    ("écrivain","écriv");
    ("égal","=");
    ("Église","E");
    ("élément","élt");
    ("encore","ag");
    ("ennemi","enne");
    ("enseigne","esg");
    ("enthousiasme","enthou");
    ("envelopp","vlpp");
    ("erreur","err");
    ("esprit","espr");
    ("être","ê");
    ("exacte","xct");
    ("exclusive","xclusv");
    ("existe","xst");
    ("existence","xstc");
    ("évangile","ev");
    ("examen","xmen");
    ("extraordinaire","extraord");
    ("fanatique","fana");
    ("fondamental","fondal");
    ("fondateur","fondat");
    ("forme","#");
    ("général","geral");
    ("grand","gd");
    ("homme","h");
    ("horreur","horr");
    ("histoire","hist");
    ("humanité","huma");
    ("humain","hu");
    ("idée","id");
    ("image","img");
    ("imagine","imgn");
    ("immédiat","dz");
    ("incarnation","incar");
    ("infini","nfn");
    ("intervention","intervo");
    ("jamais","jms");
    ("Jésus","J");
    ("Jésus-Christ","JC");
    ("jeunesse","jeuss");
    ("jour","jr");
    ("juillet","juil");
    ("langage","c++");
    ("légitime","légit");
    ("liberté","libé");
    ("Libre-Pensée","LP");
    ("livre","lvr");
    ("longtemps","lgtps");
    ("martyr","my");
    ("même","m^");
    ("méthode","mthd");
    ("moderne","mod");
    ("moins","-");
    ("monde","mnd");
    ("nature","nat");
    ("naturel","natl");
    ("néanmoins","néan");
    ("nombreux","nbrx");
    ("nous","ns");
    ("objet","obj");
    ("occasion","occas");
    ("opinion","opin");
    ("orgueil","orgu");
    ("origine","orig");
    ("orthodoxe","orthox");
    ("ouvrage","vrage");
    ("particulier","partic");
    ("par ce","pc");
    ("passion","çç");
    ("personne","ng");
    ("peuple","ple");
    ("peut-être","p-e");
    ("philologie","phlgi");
    ("philosophie","phi");
    ("plus","+");
    ("point","pt");
    ("premier","prem");
    ("principe","pzp");
    ("profond","__");
    ("prouver","prvr");
    ("public","pub");
    ("puissance","watt");
    ("puissant","wutt");
    ("quand","qd");
    ("quelque","qqe");
    ("raison","rais");
    ("rapport","/");
    ("rationaliste","ratist");
    ("rationalisme","ratism");
    ("religieux","religx");
    ("religion","relig");
    ("résultat","rés");
    ("saint Luc","sL");
    ("saint Marc","sM");
    ("saint Jean","sJ");
    ("science","sci");
    ("siècle","oo");
    ("société","soc");
    ("sous","ss");
    ("souvent","svent");
    ("souverain","svrn");
    ("succès","suc");
    ("surnaturel","surnat");
    ("surtout","surtt");
    ("système","syst");
    ("témoignage","tgng");
    ("témoin","zg");
    ("temps","tps");
    ("théologie","théoli");
    ("théorie","théor");
    ("toujours","tjs");
    ("tous","ts");
    ("tout","tt");
    ("trouver","trver");
    ("unanimité","unan");
    ("univers","univ");
    ("universel","univl");
    ("vérité","vé");
    ("valeur","val");
    ("[i]Vie de Jésus[/i]","VdJ");
    ("vous","vs");
    ("vérité","vé");
    ("vrai","vr");
    ("vainqueur","vqr");
    ("vulgaire","vulg");
    ("yeux","yx");
];
prefix_abbreviations=
[
    ("ka","qu'a");
    ("ke","qu'e");
    ("ki","qu'i");
    ("ko","qu'o");
    ("ku","qu'u");
    ("jsq","jusqu'");
];
case_insensitive_adjustable_decompressions=
[
    ("ait","ait",
[
                    ("expliqu","","expliquer");
                    ("Expliqu","","Expliquer");
]
    );
    ("aa","aire",
                  []
    );
    ("ax","eaux",
                  []
    );
    ("b","able",
[
                   ("considér","","consid");
                   ("indéstruct","ible","indéstruct");
                   ("imposs","ible","impss");
                   ("sens","ible","sens");
                   ("Considér","","Consid");
                   ("Indéstruct","ible","Indéstruct");
                   ("Imposs","ible","Impss");
                   ("Sens","ible","Sens");
]
    );
    ("blt","bilité",
[
                        ("infailli","","ifll");
                        ("impecca","","ipcc");
                        ("possi","","poss");
                        ("Infailli","","Ifll");
                        ("Impecca","","Ipcc");
                        ("Possi","","Poss");
]
    );
    ("e","e",
[
                ("ancienn","","ancien");
                ("chrétienn","","chrétien");
                ("publiqu","","public");
                ("surnaturell","","surnaturel");
                ("Ancienn","","Ancien");
                ("Chrétienn","","Chrétien");
                ("Publiqu","","Public");
                ("Surnaturell","","Surnaturel");
]
    );
    ("é","é",
[
                  ("attaqu","","attaque");
                  ("authenticit","","auth");
                  ("invoqu","","invoque");
                  ("passionn","","passion");
                  ("Attaqu","","Attaque");
                  ("Authenticit","","Auth");
                  ("Invoqu","","Invoque");
                  ("Passionn","","Passion");
]
    );
    ("ent","ent",
[
                    ("attaqu","","attaque");
                    ("exist","","existe");
                    ("invoqu","","invoque");
                    ("Attaqu","","Attaque");
                    ("Exist","","Existe");
                    ("Invoqu","","Invoque");
]
    );
    ("eur","eur",
                  []
    );
    ("f","f",
[
                ("autre","fois","autre");
                ("par","fois","par");
                ("Autre","fois","Autre");
                ("Par","fois","Par");
]
    );
    ("id","itude",
[
                     ("","idée","");
]
    );
    ("io","tion",
[
                    ("accusa","","accus");
                    ("appari","","appar");
                    ("aspira","","aspir");
                    ("conclu","sion","conclu");
                    ("condi","","cond");
                    ("considéra","","consid");
                    ("contradic","","contrad");
                    ("érudi","","érud");
                    ("imagina","","imagine");
                    ("propaga","","propag");
                    ("tradi","","trad");
                    ("Accusa","","Accus");
                    ("Appari","","Appar");
                    ("Aspira","","Aspir");
                    ("Conclu","sion","Conclu");
                    ("Condi","","Cond");
                    ("Considéra","","Consid");
                    ("Contradic","","Contrad");
                    ("Érudi","","Érud");
                    ("Imagina","","Imagine");
                    ("Propaga","","Propag");
                    ("Tradi","","Trad");
]
    );
    ("ix","ieux",
[
                    ("sér","","sr");
                    ("Sér","","Sr");
]
    );
    ("î","ître",
                   []
    );
    ("í","ité",
                  []
    );
    ("ll","elle",
[
                    ("ai","lleurs","ai");
                    ("bat","aille","bat");
                    ("natur","","nature");
                    ("personn","","personne");
                    ("Ai","lleurs","Ai");
                    ("Bat","aille","Bat");
                    ("Natur","","Nature");
                    ("Personn","","Personne");
]
    );
    ("m","ment",
[
                   ("directe","","direct");
                   ("égale","","égal");
                   ("habile","","habil");
                   ("particulière","","particulier");
                   ("raisonne","","raison");
                   ("rapproche","","rapproch");
                   ("seule","","seul");
                   ("simple","","simpl");
                   ("Directe","","Direct");
                   ("Égale","","Égal");
                   ("Habile","","Habil");
                   ("Particulière","","Particulier");
                   ("Raisonne","","Raison");
                   ("Rapproche","","Rapproch");
                   ("Seule","","Seul");
                   ("Simple","","Simpl");
]
    );
    ("mtt","mettre",
                     []
    );
    ("nc","nce",
[
                   ("différe","","différ");
                   ("éloque","","éloq");
                   ("importa","","import");
                   ("influe","","iflu");
                   ("intellige","","intellg");
                   ("obéissa","","obéiss");
                   ("préfére","","préfér");
                   ("provide","","provid");
                   ("Différe","","Différ");
                   ("Éloque","","Éloq");
                   ("Importa","","Import");
                   ("Influe","","Iflu");
                   ("Intellige","","Intellg");
                   ("Obéissa","","Obéiss");
                   ("Préfére","","Préfér");
                   ("Provide","","Provid");
]
    );
    ("nw","ctuel",
                   []
    );
    ("q","que",
[
                  ("atta","","at");
                  ("caractéristi","","caractère");
                  ("consé","quent","consé");
                  ("criti","","crt");
                  ("énergi","","énerg");
                  ("ecclésiasti","","ecc");
                  ("épo","","ép");
                  ("évangéli","","évangile");
                  ("expli","quer","xpl");
                  ("histori","","histoire");
                  ("invo","","iv");
                  ("inatta","qu","inat");
                  ("logi","","lg");
                  ("mythologi","","mytholg");
                  ("linguisti","","lingst");
                  ("liturgi","","liturg");
                  ("métaphysi","","métaphys");
                  ("par ce"," que","pc");
                  ("philosophi","","philosophie");
                  ("polémi","","polém");
                  ("pour","quoi","p");
                  ("quel","","q");
                  ("","question","");
                  ("scientifi","","science");
                  ("stratégi","","stratég");
                  ("théologi","","théol");
                  ("tragi","","trag");
                  ("Atta","","At");
                  ("Caractéristi","","Caractère");
                  ("Consé","quent","Consé");
                  ("Criti","","Crt");
                  ("Énergi","","Énerg");
                  ("Ecclésiasti","","Ecc");
                  ("Épo","","Ép");
                  ("Évangéli","","Évangile");
                  ("Expli","quer","Xpl");
                  ("Histori","","Histoire");
                  ("Invo","","Iv");
                  ("Inatta","qu","Inat");
                  ("Logi","","Lg");
                  ("Mythologi","","Mytholg");
                  ("Linguisti","","Lingst");
                  ("Liturgi","","Liturg");
                  ("Métaphysi","","Métaphys");
                  ("Par ce"," que","Pc");
                  ("Philosophi","","Philosophie");
                  ("Polémi","","Polém");
                  ("Pour","quoi","P");
                  ("Quel","","Q");
                  ("Scientifi","","Science");
                  ("Stratégi","","Stratég");
                  ("Théologi","","Théol");
                  ("Tragi","","Trag");
]
    );
    ("s","s",
              []
    );
    ("ss","esse",
                  []
    );
    ("zn","isme",
[
                    ("catholic","","catholique");
                    ("christian","","chrétien");
                    ("sceptic","","scep");
                    ("Catholic","","Catholique");
                    ("Christian","","Chrétien");
                    ("Sceptic","","Scep");
]
    );
    ("-m^","-même",
                     []
    );
    ("-vs","-vous",
                    []
    );
];
case_insensitive_inert_words=
[
    "donc";
    "idée";
    "je";
    "nom";
    "prix";
    "voix";
    "Donc";
    "Idée";
    "Je";
    "Nom";
    "Prix";
    "Voix";
];
case_insensitive_left_core_abbreviations=
[
    ("absolu","absl");
    ("abomin","abom");
    ("académie","acad");
    ("ainsi","asi");
    ("allemand","allmd");
    ("âme","â");
    ("amour","amr");
    ("ancien","anci");
    ("apocalypse","apoc");
    ("apocryphe","apocr");
    ("apôtre","apô");
    ("après","aft");
    ("aujourd'hui","auj");
    ("aveugle","avgl");
    ("beaucoup","bcp");
    ("caractère","khi");
    ("catholique","catho");
    ("c'est-à-dire","cad");
    ("cependant","ksk");
    ("c'est","di");
    ("ce n'est","din");
    ("chose","ch");
    ("cherche","chch");
    ("chercher","chchr");
    ("chrétien","chr");
    ("christianisme","chisme");
    ("collègue","collg");
    ("coup","cp");
    ("conférence","confé");
    ("contradiction","contradio");
    ("controverse","controv");
    ("croyant","croy");
    ("de","de");
    ("démonstration","démo");
    ("démontrer","démor");
    ("divinité","div");
    ("divinité du Christ","ddC");
    ("dogme","dgm");
    ("dogme de la divinité du Christ","dddC");
    ("Dieu","D");
    ("écrivain","écriv");
    ("égal","=");
    ("Église","E");
    ("élément","élt");
    ("encore","ag");
    ("ennemi","enne");
    ("enseigne","esg");
    ("enthousiasme","enthou");
    ("envelopp","vlpp");
    ("erreur","err");
    ("esprit","espr");
    ("être","ê");
    ("exacte","xct");
    ("exclusive","xclusv");
    ("existe","xst");
    ("existence","xstc");
    ("évangile","ev");
    ("examen","xmen");
    ("extraordinaire","extraord");
    ("fanatique","fana");
    ("fondamental","fondal");
    ("fondateur","fondat");
    ("forme","#");
    ("général","geral");
    ("grand","gd");
    ("homme","h");
    ("horreur","horr");
    ("histoire","hist");
    ("humanité","huma");
    ("humain","hu");
    ("idée","id");
    ("image","img");
    ("imagine","imgn");
    ("immédiat","dz");
    ("incarnation","incar");
    ("infini","nfn");
    ("intervention","intervo");
    ("jamais","jms");
    ("Jésus","J");
    ("Jésus-Christ","JC");
    ("jeunesse","jeuss");
    ("jour","jr");
    ("juillet","juil");
    ("langage","c++");
    ("légitime","légit");
    ("liberté","libé");
    ("Libre-Pensée","LP");
    ("livre","lvr");
    ("longtemps","lgtps");
    ("martyr","my");
    ("même","m^");
    ("méthode","mthd");
    ("moderne","mod");
    ("moins","-");
    ("monde","mnd");
    ("nature","nat");
    ("naturel","natl");
    ("néanmoins","néan");
    ("nombreux","nbrx");
    ("nous","ns");
    ("objet","obj");
    ("occasion","occas");
    ("opinion","opin");
    ("orgueil","orgu");
    ("origine","orig");
    ("orthodoxe","orthox");
    ("ouvrage","vrage");
    ("particulier","partic");
    ("par ce","pc");
    ("passion","çç");
    ("personne","ng");
    ("peuple","ple");
    ("peut-être","p-e");
    ("philologie","phlgi");
    ("philosophie","phi");
    ("plus","+");
    ("point","pt");
    ("premier","prem");
    ("principe","pzp");
    ("profond","__");
    ("prouver","prvr");
    ("public","pub");
    ("puissance","watt");
    ("puissant","wutt");
    ("quand","qd");
    ("quelque","qqe");
    ("raison","rais");
    ("rapport","/");
    ("rationaliste","ratist");
    ("rationalisme","ratism");
    ("religieux","religx");
    ("religion","relig");
    ("résultat","rés");
    ("saint Luc","sL");
    ("saint Marc","sM");
    ("saint Jean","sJ");
    ("science","sci");
    ("siècle","oo");
    ("société","soc");
    ("sous","ss");
    ("souvent","svent");
    ("souverain","svrn");
    ("succès","suc");
    ("surnaturel","surnat");
    ("surtout","surtt");
    ("système","syst");
    ("témoignage","tgng");
    ("témoin","zg");
    ("temps","tps");
    ("théologie","théoli");
    ("théorie","théor");
    ("toujours","tjs");
    ("tous","ts");
    ("tout","tt");
    ("trouver","trver");
    ("unanimité","unan");
    ("univers","univ");
    ("universel","univl");
    ("vérité","vé");
    ("valeur","val");
    ("[i]Vie de Jésus[/i]","VdJ");
    ("vous","vs");
    ("vérité","vé");
    ("vrai","vr");
    ("vainqueur","vqr");
    ("vulgaire","vulg");
    ("yeux","yx");
    ("Absolu","Absl");
    ("Abomin","Abom");
    ("Académie","Acad");
    ("Ainsi","Asi");
    ("Allemand","Allmd");
    ("Amour","Amr");
    ("Ancien","Anci");
    ("Apocalypse","Apoc");
    ("Apocryphe","Apocr");
    ("Apôtre","Apô");
    ("Après","Aft");
    ("Aujourd'hui","Auj");
    ("Aveugle","Avgl");
    ("Beaucoup","Bcp");
    ("Caractère","Khi");
    ("Catholique","Catho");
    ("C'est-à-dire","Cad");
    ("Cependant","Ksk");
    ("C'est","Di");
    ("Ce n'est","Din");
    ("Chose","Ch");
    ("Cherche","Chch");
    ("Chercher","Chchr");
    ("Chrétien","Chr");
    ("Christianisme","Chisme");
    ("Collègue","Collg");
    ("Coup","Cp");
    ("Conférence","Confé");
    ("Contradiction","Contradio");
    ("Controverse","Controv");
    ("Croyant","Croy");
    ("De","De");
    ("Démonstration","Démo");
    ("Démontrer","Démor");
    ("Divinité","Div");
    ("Divinité du Christ","DdC");
    ("Dogme","Dgm");
    ("Dogme de la divinité du Christ","DddC");
    ("Écrivain","Écriv");
    ("Élément","Élt");
    ("Encore","Ag");
    ("Ennemi","Enne");
    ("Enseigne","Esg");
    ("Enthousiasme","Enthou");
    ("Envelopp","Vlpp");
    ("Erreur","Err");
    ("Esprit","Espr");
    ("Exacte","Xct");
    ("Exclusive","Xclusv");
    ("Existe","Xst");
    ("Existence","Xstc");
    ("Évangile","Ev");
    ("Examen","Xmen");
    ("Extraordinaire","Extraord");
    ("Fanatique","Fana");
    ("Fondamental","Fondal");
    ("Fondateur","Fondat");
    ("Général","Geral");
    ("Grand","Gd");
    ("Homme","H");
    ("Horreur","Horr");
    ("Histoire","Hist");
    ("Humanité","Huma");
    ("Humain","Hu");
    ("Idée","Id");
    ("Image","Img");
    ("Imagine","Imgn");
    ("Immédiat","Dz");
    ("Incarnation","Incar");
    ("Infini","Nfn");
    ("Intervention","Intervo");
    ("Jamais","Jms");
    ("Jeunesse","Jeuss");
    ("Jour","Jr");
    ("Juillet","Juil");
    ("Langage","C++");
    ("Légitime","Légit");
    ("Liberté","Libé");
    ("Livre","Lvr");
    ("Longtemps","Lgtps");
    ("Martyr","My");
    ("Même","M^");
    ("Méthode","Mthd");
    ("Moderne","Mod");
    ("Monde","Mnd");
    ("Nature","Nat");
    ("Naturel","Natl");
    ("Néanmoins","Néan");
    ("Nombreux","Nbrx");
    ("Nous","Ns");
    ("Objet","Obj");
    ("Occasion","Occas");
    ("Opinion","Opin");
    ("Orgueil","Orgu");
    ("Origine","Orig");
    ("Orthodoxe","Orthox");
    ("Ouvrage","Vrage");
    ("Particulier","Partic");
    ("Par ce","Pc");
    ("Personne","Ng");
    ("Peuple","Ple");
    ("Peut-être","P-e");
    ("Philologie","Phlgi");
    ("Philosophie","Phi");
    ("Point","Pt");
    ("Premier","Prem");
    ("Principe","Pzp");
    ("Prouver","Prvr");
    ("Public","Pub");
    ("Puissance","Watt");
    ("Puissant","Wutt");
    ("Quand","Qd");
    ("Quelque","Qqe");
    ("Raison","Rais");
    ("Rationaliste","Ratist");
    ("Rationalisme","Ratism");
    ("Religieux","Religx");
    ("Religion","Relig");
    ("Résultat","Rés");
    ("Saint Luc","SL");
    ("Saint Marc","SM");
    ("Saint Jean","SJ");
    ("Science","Sci");
    ("Siècle","Oo");
    ("Société","Soc");
    ("Sous","Ss");
    ("Souvent","Svent");
    ("Souverain","Svrn");
    ("Succès","Suc");
    ("Surnaturel","Surnat");
    ("Surtout","Surtt");
    ("Système","Syst");
    ("Témoignage","Tgng");
    ("Témoin","Zg");
    ("Temps","Tps");
    ("Théologie","Théoli");
    ("Théorie","Théor");
    ("Toujours","Tjs");
    ("Tous","Ts");
    ("Tout","Tt");
    ("Trouver","Trver");
    ("Unanimité","Unan");
    ("Univers","Univ");
    ("Universel","Univl");
    ("Vérité","Vé");
    ("Valeur","Val");
    ("Vous","Vs");
    ("Vérité","Vé");
    ("Vrai","Vr");
    ("Vainqueur","Vqr");
    ("Vulgaire","Vulg");
    ("Yeux","Yx");
];
case_insensitive_prefix_abbreviations=
[
    ("ka","qu'a");
    ("ke","qu'e");
    ("ki","qu'i");
    ("ko","qu'o");
    ("ku","qu'u");
    ("jsq","jusqu'");
    ("Ka","Qu'a");
    ("Ke","Qu'e");
    ("Ki","Qu'i");
    ("Ko","Qu'o");
    ("Ku","Qu'u");
    ("Jsq","Jusqu'");
];
}
;;

(* Description of standard text lengthener ends here *)
