(*

#use"lib/Java_analysis/Jvsp_abstract_grammar/jvag_example.ml";;

*)


open Jvsp_types ;;
open Jvag_types ;;

module Private = struct 


(* Java grammar begins here *)


 let original_java_grammar = 

AL ([

   ("Abstract",Molecular([ABSTRACT_T]));
   ("AdditionalBound",Concat(["And";"InterfaceType"]));
   ("AdditiveExpression",Disjunction(["MultiplicativeExpression";"UsingPlusAdditiveExpression";"UsingMinusAdditiveExpression"]));
   ("AmbiguousName",Disjunction(["Identifier";"CompoundAmbiguousName"]));
   ("And",Molecular([AND_T]));
   ("AndExpression",Disjunction(["EqualityExpression";"CompoundAndExpression"]));
   ("AnnotatedIdentifierrPrecededByDot",Concat(["Dot";"StarredAnnotation";"Identifier"]));
   ("Annotation",Disjunction(["NormalAnnotation";"MarkerAnnotation";"SingleElementAnnotation"]));
   ("AnnotationInterfaceDeclaration",Concat(["StarredInterfaceModifier";"MolecularSnail_Inyourface_Identifier_Lc";"StarredAnnotationInterfaceMemberDeclaration";"Rc"]));
   ("AnnotationInterfaceElementDeclaration",Concat(["StarredAnnotationInterfaceElementModifier";"UnannType";"MolecularIdentifier_Lp_Rp";"OptionalDims";"OptionalDefaultValue";"Sm"]));
   ("AnnotationInterfaceElementModifier",Disjunction(["Annotation";"Public";"Abstract"]));
   ("AnnotationInterfaceMemberDeclaration",Disjunction(["AnnotationInterfaceElementDeclaration";"ConstantDeclaration";"ClassDeclaration";"InterfaceDeclaration";"Sm"]));
   ("ArgumentList",Concat(["Expression";"StarredExpressionPrecededByComma"]));
   ("ArrayAccess",Disjunction(["ShortArrayAccess";"LongArrayAccess"]));
   ("ArrayCreationExpression",Disjunction(["HaddockArrayCreationExpression";"MackerelArrayCreationExpression";"SalmonArrayCreationExpression";"TunaArrayCreationExpression"]));
   ("ArrayInitializer",Concat(["Lc";"OptionalVariableInitializerList";"OptionalCm";"Rc"]));
   ("ArrayType",Disjunction(["PrimitiveArrayType";"GlassArrayType";"PlasticArrayType"]));
   ("ArrayTypeyMethodReference",Concat(["ArrayType";"MolecularColon_Colon_New"]));
   ("Assert",Molecular([ASSERT_T]));
   ("AssertStatement",Disjunction(["WithoutColonAssertStatement";"WithColonAssertStatement"]));
   ("Assignment",Concat(["LeftHandSide";"OperatorEq";"Expression"]));
   ("AssignmentExpression",Disjunction(["ConditionalExpression";"Assignment"]));
   ("BasicCastExpression",Concat(["Lp";"PrimitiveType";"Rp";"UnaryExpression"]));
   ("BasicForStatement",Concat(["MolecularFor_Lp";"OptionalForInit";"Sm";"OptionalExpression";"Sm";"OptionalForUpdate";"Rp";"Statement"]));
   ("BasicForStatementNoShortIf",Concat(["MolecularFor_Lp";"OptionalForInit";"Sm";"OptionalExpression";"Sm";"OptionalForUpdate";"Rp";"StatementNoShortIf"]));
   ("BasicMethodHeader",Concat(["Result";"MolecularIdentifier_Lp";"OptionalReceiverParameterFollowedByComma";"OptionalFormalParameterList";"Rp";"OptionalDims";"OptionalSends"]));
   ("BasicMethodInvocation",Concat(["MethodName";"Lp";"OptionalArgumentList";"Rp"]));
   ("BasicRecordComponent",Concat(["StarredRecordComponentModifier";"UnannType";"Identifier"]));
   ("BasicSwitchBlock",Concat(["Lc";"SwitchRule";"StarredSwitchRule";"Rc"]));
   ("BasicSwitchRule",Concat(["SwitchLabel";"MolecularMinus_Gt";"Expression";"Sm"]));
   ("Block",Concat(["Lc";"OptionalBlockStatements";"Rc"]));
   ("BlockStatement",Disjunction(["LocalClassOrInterfaceDeclaration";"LocalVariableDeclarationStatement";"Statement"]));
   ("BlockStatements",Concat(["BlockStatement";"StarredBlockStatement"]));
   ("Boolean",Molecular([BOOLEAN_T]));
   ("BooleanLiteral",Molecular([BOOLEAN_LITERAL_T]));
   ("BoolyClassLiteral",Concat(["Boolean";"StarredOpenSquare";"MolecularDot_Class"]));
   ("BoolyPrimitiveType",Concat(["StarredAnnotation";"Boolean"]));
   ("Break",Molecular([BREAK_T]));
   ("BreakStatement",Concat(["Break";"OptionalIdentifier";"Sm"]));
   ("Byte",Molecular([BYTE_T]));
   ("Case",Molecular([CASE_T]));
   ("CaseConstant",Synonym("ConditionalExpression"));
   ("CaseConstantPrecededByComma",Concat(["Cm";"CaseConstant"]));
   ("CastExpression",Disjunction(["BasicCastExpression";"NonmappyCastExpression";"MappyCastExpression"]));
   ("CatchClause",Concat(["MolecularCatch_Lp";"StarredVariableModifier";"UnannClassType";"StarredClassTypePrecededByVerticalBar";"Identifier";"OptionalDims";"MolecularRp_Lb";"OptionalBlockStatements";"Rb"]));
   ("Catches",Concat(["MolecularCatch_Lp";"StarredVariableModifier";"UnannClassType";"StarredClassTypePrecededByVerticalBar";"Identifier";"OptionalDims";"MolecularRp_Lb";"OptionalBlockStatements";"Rb";"StarredCatchClause"]));
   ("Char",Molecular([CHAR_T]));
   ("CharacterLiteral",Molecular([CHARACTER_LITERAL_T]));
   ("ClassBody",Concat(["Lc";"StarredClassBodyDeclaration";"Rc"]));
   ("ClassBodyDeclaration",Disjunction(["ClassMemberDeclaration";"InstanceInitializer";"StaticInitializer";"ConstructorDeclaration"]));
   ("ClassDeclaration",Disjunction(["NormalClassDeclaration";"EnumDeclaration";"RecordDeclaration"]));
   ("ClassExtends",Concat(["Extends";"ClassType"]));
   ("ClassImplements",Concat(["Implements";"InterfaceType";"StarredInterfaceTypePrecededByComma"]));
   ("ClassInstanceCreationExpression",Disjunction(["HaddockClassInstanceCreationExpression";"MackerelClassInstanceCreationExpression";"SalmonClassInstanceCreationExpression"]));
   ("ClassLiteral",Disjunction(["UserDefinedClassLiteral";"NumericClassLiteral";"BoolyClassLiteral";"MolecularVoid_Dot_Class"]));
   ("ClassMemberDeclaration",Disjunction(["FieldDeclaration";"MethodDeclaration";"ClassDeclaration";"InterfaceDeclaration";"Sm"]));
   ("ClassModifier",Disjunction(["Annotation";"Public";"Protected";"Private";"Abstract";"Static";"Final";"Sealed";"Nonsealed";"Strictfp"]));
   ("ClassOrInterfaceType",Disjunction(["ClassType";"InterfaceType"]));
   ("ClassPermits",Concat(["Permits";"TypeName";"StarredTypeNamePrecededByComma"]));
   ("ClassType",Disjunction(["ShortClassType";"UsualClassType";"LongClassType"]));
   ("ClassTypePrecededByVerticalBar",Concat(["Or";"ClassType"]));
   ("ClassTypeyMethodReference",Concat(["ClassType";"MolecularColon_Colon";"OptionalTypeArguments";"New"]));
   ("Cm",Molecular([CM_T]));
   ("Colon",Molecular([COLON_T]));
   ("CompactConstructorDeclaration",Concat(["StarredConstructorModifier";"SimpleTypeName";"Lc";"OptionalExplicitConstructorInvocation";"OptionalBlockStatements";"Rc"]));
   ("Compl",Molecular([COMPL_T]));
   ("CompoundAmbiguousName",Concat(["AmbiguousName";"MolecularDot_Identifier"]));
   ("CompoundAndExpression",Concat(["AndExpression";"And";"EqualityExpression"]));
   ("CompoundConditionalAndExpression",Concat(["ConditionalAndExpression";"StrongAnd";"InclusiveOrExpression"]));
   ("CompoundConditionalOrExpression",Concat(["ConditionalOrExpression";"StrongOr";"ConditionalAndExpression"]));
   ("CompoundExclusiveOrExpression",Concat(["ExclusiveOrExpression";"Xor";"AndExpression"]));
   ("CompoundInclusiveOrExpression",Concat(["InclusiveOrExpression";"Or";"ExclusiveOrExpression"]));
   ("CompoundModuleName",Concat(["ModuleName";"MolecularDot_Identifier"]));
   ("CompoundPackageName",Concat(["PackageName";"MolecularDot_Identifier"]));
   ("CompoundPackageOrTypeName",Concat(["PackageOrTypeName";"MolecularDot_Identifier"]));
   ("CompoundSwitchBlock",Concat(["Lc";"StarredSwitchBlockStatementGroup";"StarredSwitchLabelFollowedByColon";"Rc"]));
   ("CompoundSwitchLabel",Concat(["Case";"CaseConstant";"StarredCaseConstantPrecededByComma"]));
   ("CompoundTypeName",Concat(["PackageOrTypeName";"Dot";"TypeIdentifier"]));
   ("Cond",Molecular([COND_T]));
   ("ConditionalAndExpression",Disjunction(["InclusiveOrExpression";"CompoundConditionalAndExpression"]));
   ("ConditionalExpression",Disjunction(["ConditionalOrExpression";"LambdalessConditionalAndExpressionConditionalExpression";"LambdafulConditionalAndExpressionConditionalExpression"]));
   ("ConditionalOrExpression",Disjunction(["ConditionalAndExpression";"CompoundConditionalOrExpression"]));
   ("ConstantDeclaration",Concat(["StarredConstantModifier";"UnannType";"Identifier";"OptionalDims";"OptionalEqualsVariableInitializer";"StarredVariableDeclaratorPrecededByComma";"Sm"]));
   ("ConstantModifier",Disjunction(["Annotation";"Public";"Static";"Final"]));
   ("ConstructorDeclaration",Concat(["StarredConstructorModifier";"OptionalTypeParameters";"SimpleTypeName";"Lp";"OptionalReceiverParameterFollowedByComma";"OptionalFormalParameterList";"Rp";"OptionalSends";"Lc";"OptionalExplicitConstructorInvocation";"OptionalBlockStatements";"Rc"]));
   ("ConstructorModifier",Disjunction(["Annotation";"Public";"Protected";"Private"]));
   ("Continue",Molecular([CONTINUE_T]));
   ("ContinueStatement",Concat(["Continue";"OptionalIdentifier";"Sm"]));
   ("Decr",Molecular([DECR_T]));
   ("Default",Molecular([DEFAULT_T]));
   ("DefaultValue",Concat(["Default";"ElementValue"]));
   ("DiamondlyMethodHeader",Concat(["Lt";"StarredTypeParameterModifier";"Identifier";"OptionalTypeBound";"StarredTypeParameterPrecededByComma";"Gt";"StarredAnnotation";"Result";"MolecularIdentifier_Lp";"OptionalReceiverParameterFollowedByComma";"OptionalFormalParameterList";"Rp";"OptionalDims";"OptionalSends"]));
   ("DimExpr",Concat(["StarredAnnotation";"Lb";"Expression";"Rb"]));
   ("Dims",Concat(["StarredAnnotation";"MolecularLb_Rb";"StarredDimsElement"]));
   ("DimsElement",Concat(["StarredAnnotation";"MolecularLb_Rb"]));
   ("Div",Molecular([DIV_T]));
   ("Doo",Molecular([DO_T]));
   ("DoStatement",Concat(["Doo";"Statement";"MolecularWhile_Lp";"Expression";"MolecularRp_Sm"]));
   ("Dot",Molecular([DOT_T]));
   ("Double",Molecular([DOUBLE_T]));
   ("ElementValue",Disjunction(["ConditionalExpression";"ElementValueArrayInitializer";"Annotation"]));
   ("ElementValueArrayInitializer",Concat(["Lc";"OptionalElementValueList";"OptionalCm";"Rc"]));
   ("ElementValueList",Concat(["ElementValue";"StarredElementValuePrecededByComma"]));
   ("ElementValuePairList",Concat(["MolecularIdentifier_Eq";"ElementValue";"StarredElementValuePairPrecededByComma"]));
   ("ElementValuePairPrecededByComma",Concat(["MolecularCm_Identifier_Eq";"ElementValue"]));
   ("ElementValuePrecededByComma",Concat(["Cm";"ElementValue"]));
   ("Else",Molecular([ELSE_T]));
   ("EmptyStatement",Synonym("Sm"));
   ("EnhancedForStatement",Concat(["MolecularFor_Lp";"StarredVariableModifier";"LocalVariableType";"Identifier";"OptionalDims";"OptionalEqualsVariableInitializer";"StarredVariableDeclaratorPrecededByComma";"Colon";"Expression";"Rp";"Statement"]));
   ("EnhancedForStatementNoShortIf",Concat(["MolecularFor_Lp";"StarredVariableModifier";"LocalVariableType";"Identifier";"OptionalDims";"OptionalEqualsVariableInitializer";"StarredVariableDeclaratorPrecededByComma";"Colon";"Expression";"Rp";"StatementNoShortIf"]));
   ("EnumBodyDeclarations",Concat(["Sm";"StarredClassBodyDeclaration"]));
   ("EnumConstantList",Concat(["StarredEnumConstantModifier";"Identifier";"OptionalParenthesedArgumentList";"OptionalClassBody";"StarredEnumConstantPrecededByComma"]));
   ("EnumConstantModifier",Synonym("Annotation"));
   ("EnumConstantPrecededByComma",Concat(["Cm";"StarredEnumConstantModifier";"Identifier";"OptionalParenthesedArgumentList";"OptionalClassBody"]));
   ("EnumDeclaration",Concat(["StarredClassModifier";"MolecularEnum_Identifier";"OptionalClassImplements";"Lc";"OptionalEnumConstantList";"OptionalCm";"OptionalEnumBodyDeclarations";"Rc"]));
   ("Eq",Molecular([EQ_T]));
   ("EqualityExpression",Disjunction(["RelationalExpression";"WithEqEqEqualityExpression";"WithExclamationEqEqualityExpression"]));
   ("EqualsVariableInitializer",Concat(["Eq";"VariableInitializer"]));
   ("ExceptionType",Disjunction(["ClassType";"TypeVariable"]));
   ("ExceptionTypePrecededByComma",Concat(["Cm";"ExceptionType"]));
   ("ExclamationEq",Molecular([NOT_EQ_T]));
   ("ExclusiveOrExpression",Disjunction(["AndExpression";"CompoundExclusiveOrExpression"]));
   ("ExplicitCallToSuperFieldAccess",Concat(["TypeName";"MolecularDot_Super_Dot_Identifier"]));
   ("ExplicitConstructorInvocation",Disjunction(["HaddockExplicitConstructorInvocation";"MackerelExplicitConstructorInvocation";"SalmonExplicitConstructorInvocation";"TunaExplicitConstructorInvocation"]));
   ("Expression",Disjunction(["LambdaExpression";"AssignmentExpression"]));
   ("ExpressionName",Disjunction(["Identifier";"CompoundAmbiguousName"]));
   ("ExpressionPrecededByComma",Concat(["Cm";"Expression"]));
   ("ExpressionStatement",Concat(["StatementExpression";"Sm"]));
   ("ExpressionyMethodInvocation",Concat(["ExpressionName";"Dot";"OptionalTypeArguments";"MolecularIdentifier_Lp";"OptionalArgumentList";"Rp"]));
   ("ExpressionyMethodReference",Concat(["ExpressionName";"MolecularColon_Colon";"OptionalTypeArguments";"Identifier"]));
   ("Extends",Molecular([EXTENDS_T]));
   ("FieldAccess",Disjunction(["SimplestFieldAccess";"MolecularSuper_Dot_Identifier";"ExplicitCallToSuperFieldAccess"]));
   ("FieldDeclaration",Concat(["StarredFieldModifier";"UnannType";"Identifier";"OptionalDims";"OptionalEqualsVariableInitializer";"StarredVariableDeclaratorPrecededByComma";"Sm"]));
   ("FieldModifier",Disjunction(["Annotation";"Public";"Protected";"Private";"Static";"Final";"Transient";"Volatile"]));
   ("Final",Molecular([FINAL_T]));
   ("Finally",Concat(["MolecularAtLast_Lb";"OptionalBlockStatements";"Rb"]));
   ("Float",Molecular([FLOAT_T]));
   ("FloatingPointLiteral",Molecular([FLOATING_POINT_LITERAL_T]));
   ("FloatingPointType",Disjunction(["Float";"Double"]));
   ("ForInit",Disjunction(["StatementExpressionList";"LocalVariableDeclaration"]));
   ("FormalParameter",Disjunction(["StrictFormalParameter";"UsualParameter"]));
   ("FormalParameterList",Concat(["FormalParameter";"StarredFormalParameterPrecededByComma"]));
   ("FormalParameterPrecededByComma",Concat(["Cm";"FormalParameter"]));
   ("ForStatement",Disjunction(["BasicForStatement";"EnhancedForStatement"]));
   ("ForStatementNoShortIf",Disjunction(["BasicForStatementNoShortIf";"EnhancedForStatementNoShortIf"]));
   ("ForUpdate",Synonym("StatementExpressionList"));
   ("Ge",Molecular([GE_T]));
   ("GlassArrayType",Concat(["ClassOrInterfaceType";"StarredAnnotation";"MolecularLb_Rb";"StarredDimsElement"]));
   ("GlassTypeBound",Concat(["Extends";"ClassOrInterfaceType";"StarredAdditionalBound"]));
   ("GlassUnannArrayType",Concat(["UnannClassOrInterfaceType";"StarredAnnotation";"MolecularLb_Rb";"StarredDimsElement"]));
   ("Gt",Molecular([GT_T]));
   ("HaddockArrayCreationExpression",Concat(["New";"PrimitiveType";"StarredAnnotation";"Lb";"Expression";"Rb";"StarredDimExpr";"OptionalDims"]));
   ("HaddockClassInstanceCreationExpression",Concat(["New";"OptionalTypeArguments";"StarredAnnotation";"Identifier";"StarredAnnotatedIdentifierrPrecededByDot";"OptionalTypeArgumentsOrDiamond";"Lp";"OptionalArgumentList";"Rp";"OptionalClassBody"]));
   ("HaddockExplicitConstructorInvocation",Concat(["OptionalTypeArguments";"MolecularThis_Lp";"OptionalArgumentList";"MolecularRp_Sm"]));
   ("HeavyLambdaParameter",Concat(["StarredVariableModifier";"LambdaParameterType";"Identifier";"OptionalDims"]));
   ("Identifier",Molecular([IDENTIFIER_T]));
   ("IdentifierFollowedByDot",Concat(["MolecularIdentifier_Dot"]));
   ("IdentifierPrecededByComma",Concat(["MolecularCm_Identifier"]));
   ("IdentifieryLambdaParameterList",Concat(["Identifier";"StarredIdentifierPrecededByComma"]));
   ("IdentifieryTypeBound",Concat(["Extends";"StarredAnnotation";"Identifier"]));
   ("IfThenElseStatement",Concat(["MolecularIf_Lp";"Expression";"Rp";"StatementNoShortIf";"Else";"Statement"]));
   ("IfThenElseStatementNoShortIf",Concat(["MolecularIf_Lp";"Expression";"Rp";"StatementNoShortIf";"Else";"StatementNoShortIf"]));
   ("IfThenStatement",Concat(["MolecularIf_Lp";"Expression";"Rp";"Statement"]));
   ("Implements",Molecular([IMPLEMENTS_T]));
   ("Import",Molecular([IMPORT_T]));
   ("ImportDeclaration",Disjunction(["SingleTypeImportDeclaration";"TypeImportOnDemandDeclaration";"SingleStaticImportDeclaration";"StaticImportOnDemandDeclaration"]));
   ("InclusiveOrExpression",Disjunction(["ExclusiveOrExpression";"CompoundInclusiveOrExpression"]));
   ("Incr",Molecular([INCR_T]));
   ("InstanceInitializer",Synonym("Block"));
   ("Instanceof",Molecular([INSTANCEOF_T]));
   ("InstanceofExpression",Disjunction(["ShortInstanceofExpression";"LongInstanceofExpression"]));
   ("Int",Molecular([INT_T]));
   ("IntegerLiteral",Molecular([INTEGER_LITERAL_T]));
   ("IntegralType",Disjunction(["Byte";"Short";"Int";"Long";"Char"]));
   ("InterfaceDeclaration",Disjunction(["NormalInterfaceDeclaration";"AnnotationInterfaceDeclaration"]));
   ("InterfaceExtends",Concat(["Extends";"InterfaceType";"StarredInterfaceTypePrecededByComma"]));
   ("InterfaceMemberDeclaration",Disjunction(["ConstantDeclaration";"InterfaceMethodDeclaration";"ClassDeclaration";"InterfaceDeclaration";"Sm"]));
   ("InterfaceMethodDeclaration",Concat(["StarredInterfaceMethodModifier";"MethodHeader";"MethodBody"]));
   ("InterfaceMethodModifier",Disjunction(["Annotation";"Public";"Private";"Abstract";"Default";"Static";"Strictfp"]));
   ("InterfaceModifier",Disjunction(["Annotation";"Public";"Protected";"Private";"Abstract";"Static";"Sealed";"Nonsealed";"Strictfp"]));
   ("InterfacePermits",Concat(["Permits";"TypeName";"StarredTypeNamePrecededByComma"]));
   ("InterfaceType",Synonym("ClassType"));
   ("InterfaceTypePrecededByComma",Concat(["Cm";"InterfaceType"]));
   ("LabeledStatement",Concat(["MolecularIdentifier_Colon";"Statement"]));
   ("LabeledStatementNoShortIf",Concat(["MolecularIdentifier_Colon";"StatementNoShortIf"]));
   ("LambdaBody",Disjunction(["Expression";"Block"]));
   ("LambdaExpression",Concat(["LambdaParameters";"MolecularMinus_Gt";"LambdaBody"]));
   ("LambdafulConditionalAndExpressionConditionalExpression",Concat(["ConditionalOrExpression";"Cond";"Expression";"Colon";"LambdaParameters";"MolecularMinus_Gt";"LambdaBody"]));
   ("LambdalessConditionalAndExpressionConditionalExpression",Concat(["ConditionalOrExpression";"Cond";"Expression";"Colon";"ConditionalExpression"]));
   ("LambdaParameter",Disjunction(["HeavyLambdaParameter";"UsualParameter"]));
   ("LambdaParameterList",Disjunction(["LambdayLambdaParameterList";"IdentifieryLambdaParameterList"]));
   ("LambdaParameterPrecededByComma",Concat(["Cm";"LambdaParameter"]));
   ("LambdaParameters",Disjunction(["ListyLambdaParameters";"Identifier"]));
   ("LambdaParameterType",Disjunction(["UnannType";"Var"]));
   ("LambdayLambdaParameterList",Concat(["LambdaParameter";"StarredLambdaParameterPrecededByComma"]));
   ("Lb",Molecular([LB_T]));
   ("Lc",Molecular([LC_T]));
   ("Le",Molecular([LE_T]));
   ("LeftHandSide",Disjunction(["ExpressionName";"FieldAccess";"ArrayAccess"]));
   ("ListyLambdaParameters",Concat(["Lp";"OptionalLambdaParameterList";"Rp"]));
   ("Literal",Disjunction(["IntegerLiteral";"FloatingPointLiteral";"BooleanLiteral";"CharacterLiteral";"StringLiteral";"TextBlock";"NullLiteral"]));
   ("LocalClassOrInterfaceDeclaration",Disjunction(["ClassDeclaration";"NormalInterfaceDeclaration"]));
   ("LocalVariableDeclaration",Concat(["StarredVariableModifier";"LocalVariableType";"Identifier";"OptionalDims";"OptionalEqualsVariableInitializer";"StarredVariableDeclaratorPrecededByComma"]));
   ("LocalVariableDeclarationStatement",Concat(["StarredVariableModifier";"LocalVariableType";"Identifier";"OptionalDims";"OptionalEqualsVariableInitializer";"StarredVariableDeclaratorPrecededByComma";"Sm"]));
   ("LocalVariableType",Disjunction(["UnannType";"Var"]));
   ("Long",Molecular([LONG_T]));
   ("LongArrayAccess",Concat(["PrimaryNoNewArray";"Lb";"Expression";"Rb"]));
   ("LongClassType",Concat(["ClassOrInterfaceType";"Dot";"StarredAnnotation";"TypeIdentifier";"OptionalTypeArguments"]));
   ("LongInstanceofExpression",Concat(["RelationalExpression";"Instanceof";"Pattern"]));
   ("LongTryStatement",Concat(["MolecularTry_Lb";"OptionalBlockStatements";"MolecularRb_Catch_Lp";"StarredVariableModifier";"UnannClassType";"StarredClassTypePrecededByVerticalBar";"Identifier";"OptionalDims";"MolecularRp_Lb";"OptionalBlockStatements";"Rb";"StarredCatchClause"]));
   ("LongUnannClassType",Concat(["UnannClassOrInterfaceType";"Dot";"StarredAnnotation";"TypeIdentifier";"OptionalTypeArguments"]));
   ("Lp",Molecular([LP_T]));
   ("Ls",Molecular([LS_T]));
   ("Lt",Molecular([LT_T]));
   ("MackerelArrayCreationExpression",Concat(["New";"ClassOrInterfaceType";"StarredAnnotation";"Lb";"Expression";"Rb";"StarredDimExpr";"OptionalDims"]));
   ("MackerelClassInstanceCreationExpression",Concat(["ExpressionName";"MolecularDot_New";"OptionalTypeArguments";"StarredAnnotation";"Identifier";"StarredAnnotatedIdentifierrPrecededByDot";"OptionalTypeArgumentsOrDiamond";"Lp";"OptionalArgumentList";"Rp";"OptionalClassBody"]));
   ("MackerelExplicitConstructorInvocation",Concat(["OptionalTypeArguments";"MolecularSuper_Lp";"OptionalArgumentList";"MolecularRp_Sm"]));
   ("MappyCastExpression",Concat(["Lp";"ReferenceType";"StarredAdditionalBound";"Rp";"LambdaParameters";"MolecularMinus_Gt";"LambdaBody"]));
   ("MarkerAnnotation",Concat(["Snail";"TypeName"]));
   ("MethodBody",Disjunction(["Block";"Sm"]));
   ("MethodDeclaration",Concat(["StarredMethodModifier";"MethodHeader";"MethodBody"]));
   ("MethodHeader",Disjunction(["BasicMethodHeader";"DiamondlyMethodHeader"]));
   ("MethodInvocation",Disjunction(["BasicMethodInvocation";"TypeyMethodInvocation";"ExpressionyMethodInvocation";"PrimaryyMethodInvocation";"ThisSuperMethodInvocation";"OtherSuperMethodInvocation"]));
   ("MethodModifier",Disjunction(["Annotation";"Public";"Protected";"Private";"Abstract";"Static";"Final";"Synchronized";"Native";"Strictfp"]));
   ("MethodName",Synonym("Identifier"));
   ("MethodReference",Disjunction(["ExpressionyMethodReference";"PrimaryyMethodReference";"ReferenceTypeyMethodReference";"ThisSuperMethodReference";"TypeNameyMethodReference";"ClassTypeyMethodReference";"ArrayTypeyMethodReference"]));
   ("Minus",Molecular([MINUS_T]));
   ("Mod",Molecular([MOD_T]));
   ("ModuleName",Disjunction(["Identifier";"CompoundModuleName"]));
   ("MolecularAtLast_Lb",Molecular([FINALLY_T;LB_T]));
   ("MolecularCatch_Lp",Molecular([CATCH_T;LP_T]));
   ("MolecularClass_Identifier",Molecular([CLASS_T;IDENTIFIER_T]));
   ("MolecularCm_Identifier",Molecular([CM_T;IDENTIFIER_T]));
   ("MolecularCm_Identifier_Eq",Molecular([CM_T;IDENTIFIER_T;EQ_T]));
   ("MolecularColon_Colon",Molecular([COLON_T;COLON_T]));
   ("MolecularColon_Colon_New",Molecular([COLON_T;COLON_T;NEW_T]));
   ("MolecularDot_Class",Molecular([DOT_T;CLASS_T]));
   ("MolecularDot_Dot_Dot_Identifier",Molecular([DOT_T;DOT_T;DOT_T;IDENTIFIER_T]));
   ("MolecularDot_Identifier",Molecular([DOT_T;IDENTIFIER_T]));
   ("MolecularDot_Identifier_Sm",Molecular([DOT_T;IDENTIFIER_T;SM_T]));
   ("MolecularDot_New",Molecular([DOT_T;NEW_T]));
   ("MolecularDot_Super_Colon_Colon",Molecular([DOT_T;SUPER_T;COLON_T;COLON_T]));
   ("MolecularDot_Super_Dot",Molecular([DOT_T;SUPER_T;DOT_T]));
   ("MolecularDot_Super_Dot_Identifier",Molecular([DOT_T;SUPER_T;DOT_T;IDENTIFIER_T]));
   ("MolecularDot_This",Molecular([DOT_T;THIS_T]));
   ("MolecularDot_Times_Sm",Molecular([DOT_T;TIMES_T;SM_T]));
   ("MolecularEnum_Identifier",Molecular([ENUM_T;IDENTIFIER_T]));
   ("MolecularFor_Lp",Molecular([FOR_T;LP_T]));
   ("MolecularIdentifier_Colon",Molecular([IDENTIFIER_T;COLON_T]));
   ("MolecularIdentifier_Dot",Molecular([IDENTIFIER_T;DOT_T]));
   ("MolecularIdentifier_Eq",Molecular([IDENTIFIER_T;EQ_T]));
   ("MolecularIdentifier_Lp",Molecular([IDENTIFIER_T;LP_T]));
   ("MolecularIdentifier_Lp_Rp",Molecular([IDENTIFIER_T;LP_T;RP_T]));
   ("MolecularIf_Lp",Molecular([IF_T;LP_T]));
   ("MolecularImport_Static",Molecular([IMPORT_T;STATIC_T]));
   ("MolecularInyourface_Identifier",Molecular([INTERFACE_T;IDENTIFIER_T]));
   ("MolecularLb_Rb",Molecular([LB_T;RB_T]));
   ("MolecularLt_Gt",Molecular([LT_T;GT_T]));
   ("MolecularMinus_Gt",Molecular([MINUS_T;GT_T]));
   ("MolecularMinus_Gt_Lb",Molecular([MINUS_T;GT_T;LB_T]));
   ("MolecularMinus_Gt_Throw",Molecular([MINUS_T;GT_T;THROW_T]));
   ("MolecularPackage_Identifier",Molecular([PACKAGE_T;IDENTIFIER_T]));
   ("MolecularRb_Catch_Lp",Molecular([RB_T;CATCH_T;LP_T]));
   ("MolecularRecord_Identifier",Molecular([RECORD_T;IDENTIFIER_T]));
   ("MolecularRp_Lb",Molecular([RP_T;LB_T]));
   ("MolecularRp_Sm",Molecular([RP_T;SM_T]));
   ("MolecularSnail_Inyourface_Identifier_Lc",Molecular([SNAIL_T;INTERFACE_T;IDENTIFIER_T;LC_T]));
   ("MolecularStatic_Lc",Molecular([STATIC_T;LC_T]));
   ("MolecularSuper_Colon_Colon",Molecular([SUPER_T;COLON_T;COLON_T]));
   ("MolecularSuper_Dot",Molecular([SUPER_T;DOT_T]));
   ("MolecularSuper_Dot_Identifier",Molecular([SUPER_T;DOT_T;IDENTIFIER_T]));
   ("MolecularSuper_Lp",Molecular([SUPER_T;LP_T]));
   ("MolecularSwitch_Lp",Molecular([SWITCH_T;LP_T]));
   ("MolecularSynchronized_Lp",Molecular([SYNCHRONIZED_T;LP_T]));
   ("MolecularThis_Cm",Molecular([THIS_T;CM_T]));
   ("MolecularThis_Lp",Molecular([THIS_T;LP_T]));
   ("MolecularTry_Lb",Molecular([TRY_T;LB_T]));
   ("MolecularTry_Lp",Molecular([TRY_T;LP_T]));
   ("MolecularVoid_Dot_Class",Molecular([VOID_T;DOT_T;CLASS_T]));
   ("MolecularWhile_Lp",Molecular([WHILE_T;LP_T]));
   ("MultiplicativeExpression",Disjunction(["UnaryExpression";"UsingTimesMultiplicativeExpression";"UsingDivMultiplicativeExpression";"UsingModMultiplicativeExpression"]));
   ("Native",Molecular([NATIVE_T]));
   ("New",Molecular([NEW_T]));
   ("NonEmptyTypeArgumentsOrDiamond",Concat(["Lt";"TypeArgument";"StarredTypeArgumentPrecededByComma";"Gt"]));
   ("NonmappyCastExpression",Concat(["Lp";"ReferenceType";"StarredAdditionalBound";"Rp";"UnaryExpressionNotPlusMinus"]));
   ("Nonsealed",Molecular([NONSEALED_T]));
   ("NormalAnnotation",Concat(["Snail";"TypeName";"Lp";"OptionalElementValuePairList";"Rp"]));
   ("NormalClassDeclaration",Concat(["StarredClassModifier";"MolecularClass_Identifier";"OptionalTypeParameters";"OptionalClassExtends";"OptionalClassImplements";"OptionalClassPermits";"Lc";"StarredClassBodyDeclaration";"Rc"]));
   ("NormalInterfaceDeclaration",Concat(["StarredInterfaceModifier";"MolecularInyourface_Identifier";"OptionalTypeParameters";"OptionalInterfaceExtends";"OptionalInterfacePermits";"Lc";"StarredInterfaceMemberDeclaration";"Rc"]));
   ("Not",Molecular([NOT_T]));
   ("NullLiteral",Molecular([NULL_LITERAL_T]));
   ("NumericClassLiteral",Concat(["NumericType";"StarredOpenSquare";"MolecularDot_Class"]));
   ("NumericType",Disjunction(["IntegralType";"FloatingPointType"]));
   ("NumericyPrimitiveType",Concat(["StarredAnnotation";"NumericType"]));
   ("OpenSquare",Concat(["MolecularLb_Rb"]));
   ("OperatorEq",Molecular([OPERATOR_EQ_T]));
   ("OptionalArgumentList",Optional("ArgumentList"));
   ("OptionalBlockStatements",Optional("BlockStatements"));
   ("OptionalCatches",Optional("Catches"));
   ("OptionalClassBody",Optional("ClassBody"));
   ("OptionalClassExtends",Optional("ClassExtends"));
   ("OptionalClassImplements",Optional("ClassImplements"));
   ("OptionalClassPermits",Optional("ClassPermits"));
   ("OptionalCm",Optional("Cm"));
   ("OptionalDefaultValue",Optional("DefaultValue"));
   ("OptionalDims",Optional("Dims"));
   ("OptionalElementValueList",Optional("ElementValueList"));
   ("OptionalElementValuePairList",Optional("ElementValuePairList"));
   ("OptionalEnumBodyDeclarations",Optional("EnumBodyDeclarations"));
   ("OptionalEnumConstantList",Optional("EnumConstantList"));
   ("OptionalEqualsVariableInitializer",Optional("EqualsVariableInitializer"));
   ("OptionalExplicitConstructorInvocation",Optional("ExplicitConstructorInvocation"));
   ("OptionalExpression",Optional("Expression"));
   ("OptionalFinally",Optional("Finally"));
   ("OptionalForInit",Optional("ForInit"));
   ("OptionalFormalParameterList",Optional("FormalParameterList"));
   ("OptionalForUpdate",Optional("ForUpdate"));
   ("OptionalIdentifier",Optional("Identifier"));
   ("OptionalIdentifierFollowedByDot",Optional("IdentifierFollowedByDot"));
   ("OptionalInterfaceExtends",Optional("InterfaceExtends"));
   ("OptionalInterfacePermits",Optional("InterfacePermits"));
   ("OptionalLambdaParameterList",Optional("LambdaParameterList"));
   ("OptionalPackageDeclaration",Optional("PackageDeclaration"));
   ("OptionalParenthesedArgumentList",Optional("ParenthesedArgumentList"));
   ("OptionalReceiverParameterFollowedByComma",Optional("ReceiverParameterFollowedByComma"));
   ("OptionalRecordComponentList",Optional("RecordComponentList"));
   ("OptionalSends",Optional("Sends"));
   ("OptionalSm",Optional("Sm"));
   ("OptionalTypeArguments",Optional("TypeArguments"));
   ("OptionalTypeArgumentsOrDiamond",Optional("TypeArgumentsOrDiamond"));
   ("OptionalTypeBound",Optional("TypeBound"));
   ("OptionalTypeParameters",Optional("TypeParameters"));
   ("OptionalVariableInitializerList",Optional("VariableInitializerList"));
   ("OptionalWildcardBounds",Optional("WildcardBounds"));
   ("Or",Molecular([OR_T]));
   ("OrdinaryCompilationUnit",Concat(["OptionalPackageDeclaration";"StarredImportDeclaration";"StarredTopLevelClassOrInterfaceDeclaration"]));
   ("OtherSuperMethodInvocation",Concat(["TypeName";"MolecularDot_Super_Dot";"OptionalTypeArguments";"MolecularIdentifier_Lp";"OptionalArgumentList";"Rp"]));
   ("PackageDeclaration",Concat(["StarredPackageModifier";"MolecularPackage_Identifier";"StarredMolecularDot_Identifier";"Sm"]));
   ("PackageModifier",Synonym("Annotation"));
   ("PackageName",Disjunction(["Identifier";"CompoundPackageName"]));
   ("PackageOrTypeName",Disjunction(["Identifier";"CompoundPackageOrTypeName"]));
   ("ParenthesedArgumentList",Concat(["Lp";"OptionalArgumentList";"Rp"]));
   ("ParenthesedPrimaryNoNewArray",Concat(["Lp";"Expression";"Rp"]));
   ("ParenthesedTryStatement",Concat(["MolecularTry_Lp";"Resource";"StarredResourcePrecededBySemiColon";"OptionalSm";"MolecularRp_Lb";"OptionalBlockStatements";"Rb";"OptionalCatches";"OptionalFinally"]));
   ("Pattern",Synonym("TypePattern"));
   ("Permits",Molecular([PERMITS_T]));
   ("PlasticArrayType",Concat(["StarredAnnotation";"Identifier";"StarredAnnotation";"MolecularLb_Rb";"StarredDimsElement"]));
   ("Plus",Molecular([PLUS_T]));
   ("PostDecrementExpression",Concat(["PostfixExpression";"Decr"]));
   ("PostfixExpression",Disjunction(["Primary";"ExpressionName";"PostIncrementExpression";"PostDecrementExpression"]));
   ("PostIncrementExpression",Concat(["PostfixExpression";"Incr"]));
   ("PreDecrementExpression",Concat(["Decr";"UnaryExpression"]));
   ("PreIncrementExpression",Concat(["Incr";"UnaryExpression"]));
   ("Primary",Disjunction(["PrimaryNoNewArray";"ArrayCreationExpression"]));
   ("PrimaryNoNewArray",Disjunction(["Literal";"ClassLiteral";"This";"UsingThisPrimaryNoNewArray";"ParenthesedPrimaryNoNewArray";"ClassInstanceCreationExpression";"FieldAccess";"ArrayAccess";"MethodInvocation";"MethodReference"]));
   ("PrimaryyMethodInvocation",Concat(["Primary";"Dot";"OptionalTypeArguments";"MolecularIdentifier_Lp";"OptionalArgumentList";"Rp"]));
   ("PrimaryyMethodReference",Concat(["Primary";"MolecularColon_Colon";"OptionalTypeArguments";"Identifier"]));
   ("PrimitiveArrayType",Concat(["PrimitiveType";"StarredAnnotation";"MolecularLb_Rb";"StarredDimsElement"]));
   ("PrimitiveType",Disjunction(["NumericyPrimitiveType";"BoolyPrimitiveType"]));
   ("PrimitiveyUnannArrayType",Concat(["UnannPrimitiveType";"StarredAnnotation";"MolecularLb_Rb";"StarredDimsElement"]));
   ("Private",Molecular([PRIVATE_T]));
   ("Protected",Molecular([PROTECTED_T]));
   ("Public",Molecular([PUBLIC_T]));
   ("Rb",Molecular([RB_T]));
   ("Rc",Molecular([RC_T]));
   ("ReceiverParameterFollowedByComma",Concat(["StarredAnnotation";"UnannType";"OptionalIdentifierFollowedByDot";"MolecularThis_Cm"]));
   ("RecordBodyDeclaration",Disjunction(["ClassBodyDeclaration";"CompactConstructorDeclaration"]));
   ("RecordComponent",Disjunction(["BasicRecordComponent";"UsingThreeDotsRecordComponent"]));
   ("RecordComponentList",Concat(["RecordComponent";"StarredRecordComponentPrecededByComma"]));
   ("RecordComponentModifier",Synonym("Annotation"));
   ("RecordComponentPrecededByComma",Concat(["Cm";"RecordComponent"]));
   ("RecordDeclaration",Concat(["StarredClassModifier";"MolecularRecord_Identifier";"OptionalTypeParameters";"Lp";"OptionalRecordComponentList";"Rp";"OptionalClassImplements";"Lc";"StarredRecordBodyDeclaration";"Rc"]));
   ("ReferenceType",Disjunction(["ClassOrInterfaceType";"TypeVariable";"ArrayType"]));
   ("ReferenceTypeyMethodReference",Concat(["ReferenceType";"MolecularColon_Colon";"OptionalTypeArguments";"Identifier"]));
   ("RelationalExpression",Disjunction(["ShiftExpression";"UsingLtRelationalExpression";"UsingGtRelationalExpression";"UsingLeRelationalExpression";"UsingGeRelationalExpression";"InstanceofExpression"]));
   ("Resource",Disjunction(["LocalVariableDeclaration";"VariableAccess"]));
   ("ResourcePrecededBySemiColon",Concat(["Sm";"Resource"]));
   ("Result",Disjunction(["UnannType";"Void"]));
   ("Return",Molecular([RETURN_T]));
   ("ReturnStatement",Concat(["Return";"OptionalExpression";"Sm"]));
   ("Rp",Molecular([RP_T]));
   ("SalmonArrayCreationExpression",Concat(["New";"PrimitiveType";"StarredAnnotation";"MolecularLb_Rb";"StarredDimsElement";"Lc";"OptionalVariableInitializerList";"OptionalCm";"Rc"]));
   ("SalmonClassInstanceCreationExpression",Concat(["Primary";"MolecularDot_New";"OptionalTypeArguments";"StarredAnnotation";"Identifier";"StarredAnnotatedIdentifierrPrecededByDot";"OptionalTypeArgumentsOrDiamond";"Lp";"OptionalArgumentList";"Rp";"OptionalClassBody"]));
   ("SalmonExplicitConstructorInvocation",Concat(["ExpressionName";"Dot";"OptionalTypeArguments";"MolecularSuper_Lp";"OptionalArgumentList";"MolecularRp_Sm"]));
   ("Sealed",Molecular([SEALED_T]));
   ("Sends",Molecular([THROWS_T]));
   ("Sends",Concat(["Sends";"ExceptionType";"StarredExceptionTypePrecededByComma"]));
   ("ShiftExpression",Disjunction(["AdditiveExpression";"UsingLsShiftExpression";"UsingSrsShiftExpression";"UsingUrsShiftExpression"]));
   ("Short",Molecular([SHORT_T]));
   ("ShortArrayAccess",Concat(["ExpressionName";"Lb";"Expression";"Rb"]));
   ("ShortClassType",Concat(["StarredAnnotation";"TypeIdentifier";"OptionalTypeArguments"]));
   ("ShortInstanceofExpression",Concat(["RelationalExpression";"Instanceof";"ReferenceType"]));
   ("ShortTryStatement",Concat(["MolecularTry_Lb";"OptionalBlockStatements";"Rb";"OptionalCatches";"MolecularAtLast_Lb";"OptionalBlockStatements";"Rb"]));
   ("ShortUnannClassType",Concat(["TypeIdentifier";"OptionalTypeArguments"]));
   ("SimplestFieldAccess",Concat(["Primary";"MolecularDot_Identifier"]));
   ("SimpleTypeName",Synonym("Identifier"));
   ("SingleElementAnnotation",Concat(["Snail";"TypeName";"Lp";"ElementValue";"Rp"]));
   ("SingleStaticImportDeclaration",Concat(["MolecularImport_Static";"TypeName";"MolecularDot_Identifier_Sm"]));
   ("SingleTypeImportDeclaration",Concat(["Import";"TypeName";"Sm"]));
   ("Sm",Molecular([SM_T]));
   ("Snail",Molecular([SNAIL_T]));
   ("Srs",Molecular([SRS_T]));
   ("StarredAdditionalBound",Star("AdditionalBound"));
   ("StarredAnnotatedIdentifierrPrecededByDot",Star("AnnotatedIdentifierrPrecededByDot"));
   ("StarredAnnotation",Star("Annotation"));
   ("StarredAnnotationInterfaceElementModifier",Star("AnnotationInterfaceElementModifier"));
   ("StarredAnnotationInterfaceMemberDeclaration",Star("AnnotationInterfaceMemberDeclaration"));
   ("StarredBlockStatement",Star("BlockStatement"));
   ("StarredCaseConstantPrecededByComma",Star("CaseConstantPrecededByComma"));
   ("StarredCatchClause",Star("CatchClause"));
   ("StarredClassBodyDeclaration",Star("ClassBodyDeclaration"));
   ("StarredClassModifier",Star("ClassModifier"));
   ("StarredClassTypePrecededByVerticalBar",Star("ClassTypePrecededByVerticalBar"));
   ("StarredConstantModifier",Star("ConstantModifier"));
   ("StarredConstructorModifier",Star("ConstructorModifier"));
   ("StarredDimExpr",Star("DimExpr"));
   ("StarredDimsElement",Star("DimsElement"));
   ("StarredElementValuePairPrecededByComma",Star("ElementValuePairPrecededByComma"));
   ("StarredElementValuePrecededByComma",Star("ElementValuePrecededByComma"));
   ("StarredEnumConstantModifier",Star("EnumConstantModifier"));
   ("StarredEnumConstantPrecededByComma",Star("EnumConstantPrecededByComma"));
   ("StarredExceptionTypePrecededByComma",Star("ExceptionTypePrecededByComma"));
   ("StarredExpressionPrecededByComma",Star("ExpressionPrecededByComma"));
   ("StarredFieldModifier",Star("FieldModifier"));
   ("StarredFormalParameterPrecededByComma",Star("FormalParameterPrecededByComma"));
   ("StarredIdentifierPrecededByComma",Star("IdentifierPrecededByComma"));
   ("StarredImportDeclaration",Star("ImportDeclaration"));
   ("StarredInterfaceMemberDeclaration",Star("InterfaceMemberDeclaration"));
   ("StarredInterfaceMethodModifier",Star("InterfaceMethodModifier"));
   ("StarredInterfaceModifier",Star("InterfaceModifier"));
   ("StarredInterfaceTypePrecededByComma",Star("InterfaceTypePrecededByComma"));
   ("StarredLambdaParameterPrecededByComma",Star("LambdaParameterPrecededByComma"));
   ("StarredMethodModifier",Star("MethodModifier"));
   ("StarredMolecularDot_Identifier",Star("MolecularDot_Identifier"));
   ("StarredOpenSquare",Star("OpenSquare"));
   ("StarredPackageModifier",Star("PackageModifier"));
   ("StarredRecordBodyDeclaration",Star("RecordBodyDeclaration"));
   ("StarredRecordComponentModifier",Star("RecordComponentModifier"));
   ("StarredRecordComponentPrecededByComma",Star("RecordComponentPrecededByComma"));
   ("StarredResourcePrecededBySemiColon",Star("ResourcePrecededBySemiColon"));
   ("StarredStatementExpressionPrecededByComma",Star("StatementExpressionPrecededByComma"));
   ("StarredSwitchBlockStatementGroup",Star("SwitchBlockStatementGroup"));
   ("StarredSwitchLabelFollowedByColon",Star("SwitchLabelFollowedByColon"));
   ("StarredSwitchRule",Star("SwitchRule"));
   ("StarredTopLevelClassOrInterfaceDeclaration",Star("TopLevelClassOrInterfaceDeclaration"));
   ("StarredTypeArgumentPrecededByComma",Star("TypeArgumentPrecededByComma"));
   ("StarredTypeNamePrecededByComma",Star("TypeNamePrecededByComma"));
   ("StarredTypeParameterModifier",Star("TypeParameterModifier"));
   ("StarredTypeParameterPrecededByComma",Star("TypeParameterPrecededByComma"));
   ("StarredVariableDeclaratorPrecededByComma",Star("VariableDeclaratorPrecededByComma"));
   ("StarredVariableInitializerPrecededByComma",Star("VariableInitializerPrecededByComma"));
   ("StarredVariableModifier",Star("VariableModifier"));
   ("Statement",Disjunction(["StatementWithoutTrailingSubstatement";"LabeledStatement";"IfThenStatement";"IfThenElseStatement";"WhileStatement";"ForStatement"]));
   ("StatementExpression",Disjunction(["Assignment";"PreIncrementExpression";"PreDecrementExpression";"PostIncrementExpression";"PostDecrementExpression";"MethodInvocation";"ClassInstanceCreationExpression"]));
   ("StatementExpressionList",Concat(["StatementExpression";"StarredStatementExpressionPrecededByComma"]));
   ("StatementExpressionPrecededByComma",Concat(["Cm";"StatementExpression"]));
   ("StatementNoShortIf",Disjunction(["StatementWithoutTrailingSubstatement";"LabeledStatementNoShortIf";"IfThenElseStatementNoShortIf";"WhileStatementNoShortIf";"ForStatementNoShortIf"]));
   ("StatementWithoutTrailingSubstatement",Disjunction(["Block";"EmptyStatement";"ExpressionStatement";"AssertStatement";"SwitchStatement";"DoStatement";"BreakStatement";"ContinueStatement";"ReturnStatement";"SynchronizedStatement";"ThrowStatement";"TryStatement";"YieldStatement"]));
   ("Static",Molecular([STATIC_T]));
   ("StaticImportOnDemandDeclaration",Concat(["MolecularImport_Static";"TypeName";"MolecularDot_Times_Sm"]));
   ("StaticInitializer",Concat(["MolecularStatic_Lc";"OptionalBlockStatements";"Rc"]));
   ("Strictfp",Molecular([STRICTFP_T]));
   ("StrictFormalParameter",Concat(["StarredVariableModifier";"UnannType";"Identifier";"OptionalDims"]));
   ("StringLiteral",Molecular([STRING_LITERAL_T]));
   ("StrongAnd",Molecular([AND_AND_T]));
   ("StrongEq",Molecular([EQ_EQ_T]));
   ("StrongOr",Molecular([OR_OR_T]));
   ("Super",Molecular([SUPER_T]));
   ("SwitchBlock",Disjunction(["BasicSwitchBlock";"CompoundSwitchBlock"]));
   ("SwitchBlockStatementGroup",Concat(["SwitchLabel";"Colon";"StarredSwitchLabelFollowedByColon";"BlockStatement";"StarredBlockStatement"]));
   ("SwitchedUnaryExpressionNotPlusMinus",Concat(["MolecularSwitch_Lp";"Expression";"Rp";"SwitchBlock"]));
   ("SwitchLabel",Disjunction(["CompoundSwitchLabel";"Default"]));
   ("SwitchLabelFollowedByColon",Concat(["SwitchLabel";"Colon"]));
   ("SwitchRule",Disjunction(["BasicSwitchRule";"UsingBracketsSwitchRule";"UsingAThrowSwitchRule"]));
   ("SwitchStatement",Concat(["MolecularSwitch_Lp";"Expression";"Rp";"SwitchBlock"]));
   ("Synchronized",Molecular([SYNCHRONIZED_T]));
   ("SynchronizedStatement",Concat(["MolecularSynchronized_Lp";"Expression";"MolecularRp_Lb";"OptionalBlockStatements";"Rb"]));
   ("TextBlock",Molecular([TEXT_BLOCK_T]));
   ("This",Molecular([THIS_T]));
   ("ThisSuperMethodInvocation",Concat(["MolecularSuper_Dot";"OptionalTypeArguments";"MolecularIdentifier_Lp";"OptionalArgumentList";"Rp"]));
   ("ThisSuperMethodReference",Concat(["MolecularSuper_Colon_Colon";"OptionalTypeArguments";"Identifier"]));
   ("Throw",Molecular([THROW_T]));
   ("ThrowStatement",Concat(["Throw";"Expression";"Sm"]));
   ("Times",Molecular([TIMES_T]));
   ("TopLevelClassOrInterfaceDeclaration",Disjunction(["ClassDeclaration";"InterfaceDeclaration";"Sm"]));
   ("Transient",Molecular([TRANSIENT_T]));
   ("TryStatement",Disjunction(["LongTryStatement";"ShortTryStatement";"ParenthesedTryStatement"]));
   ("TunaArrayCreationExpression",Concat(["New";"ClassOrInterfaceType";"StarredAnnotation";"MolecularLb_Rb";"StarredDimsElement";"Lc";"OptionalVariableInitializerList";"OptionalCm";"Rc"]));
   ("TunaExplicitConstructorInvocation",Concat(["Primary";"Dot";"OptionalTypeArguments";"MolecularSuper_Lp";"OptionalArgumentList";"MolecularRp_Sm"]));
   ("TypeArgument",Disjunction(["ReferenceType";"Wildcard"]));
   ("TypeArgumentPrecededByComma",Concat(["Cm";"TypeArgument"]));
   ("TypeArguments",Concat(["Lt";"TypeArgument";"StarredTypeArgumentPrecededByComma";"Gt"]));
   ("TypeArgumentsOrDiamond",Disjunction(["NonEmptyTypeArgumentsOrDiamond";"MolecularLt_Gt"]));
   ("TypeBound",Disjunction(["IdentifieryTypeBound";"GlassTypeBound"]));
   ("TypeIdentifier",Synonym("Identifier"));
   ("TypeImportOnDemandDeclaration",Concat(["Import";"PackageOrTypeName";"MolecularDot_Times_Sm"]));
   ("TypeName",Disjunction(["TypeIdentifier";"CompoundTypeName"]));
   ("TypeNamePrecededByComma",Concat(["Cm";"TypeName"]));
   ("TypeNameyMethodReference",Concat(["TypeName";"MolecularDot_Super_Colon_Colon";"OptionalTypeArguments";"Identifier"]));
   ("TypeParameterModifier",Synonym("Annotation"));
   ("TypeParameterPrecededByComma",Concat(["Cm";"StarredTypeParameterModifier";"Identifier";"OptionalTypeBound"]));
   ("TypeParameters",Concat(["Lt";"StarredTypeParameterModifier";"Identifier";"OptionalTypeBound";"StarredTypeParameterPrecededByComma";"Gt"]));
   ("TypePattern",Synonym("LocalVariableDeclaration"));
   ("TypeVariable",Concat(["StarredAnnotation";"Identifier"]));
   ("TypeyMethodInvocation",Concat(["TypeName";"Dot";"OptionalTypeArguments";"MolecularIdentifier_Lp";"OptionalArgumentList";"Rp"]));
   ("TypeyUnannArrayType",Concat(["UnannTypeVariable";"StarredAnnotation";"MolecularLb_Rb";"StarredDimsElement"]));
   ("UnannArrayType",Disjunction(["PrimitiveyUnannArrayType";"GlassUnannArrayType";"TypeyUnannArrayType"]));
   ("UnannClassOrInterfaceType",Disjunction(["UnannClassType";"UnannInterfaceType"]));
   ("UnannClassType",Disjunction(["ShortUnannClassType";"UsualClassType";"LongUnannClassType"]));
   ("UnannInterfaceType",Synonym("UnannClassType"));
   ("UnannPrimitiveType",Disjunction(["NumericType";"Boolean"]));
   ("UnannReferenceType",Disjunction(["UnannClassOrInterfaceType";"UnannTypeVariable";"UnannArrayType"]));
   ("UnannType",Disjunction(["UnannPrimitiveType";"UnannReferenceType"]));
   ("UnannTypeVariable",Synonym("Identifier"));
   ("UnaryExpression",Disjunction(["UsingIncrUnaryExpression";"UsingDecrUnaryExpression";"UsingPlusUnaryExpression";"UsingMinusUnaryExpression";"UnaryExpressionNotPlusMinus"]));
   ("UnaryExpressionNotPlusMinus",Disjunction(["PostfixExpression";"UsingComplUnaryExpressionNotPlusMinus";"UsingNotUnaryExpressionNotPlusMinus";"CastExpression";"SwitchedUnaryExpressionNotPlusMinus"]));
   ("Urs",Molecular([URS_T]));
   ("UserDefinedClassLiteral",Concat(["TypeName";"StarredOpenSquare";"MolecularDot_Class"]));
   ("UsingAThrowSwitchRule",Concat(["SwitchLabel";"MolecularMinus_Gt_Throw";"Expression";"Sm"]));
   ("UsingBracketsSwitchRule",Concat(["SwitchLabel";"MolecularMinus_Gt_Lb";"OptionalBlockStatements";"Rb"]));
   ("UsingComplUnaryExpressionNotPlusMinus",Concat(["Compl";"UnaryExpression"]));
   ("UsingDecrUnaryExpression",Concat(["Decr";"UnaryExpression"]));
   ("UsingDivMultiplicativeExpression",Concat(["MultiplicativeExpression";"Div";"UnaryExpression"]));
   ("UsingExtendsWildcardBounds",Concat(["Extends";"ReferenceType"]));
   ("UsingGeRelationalExpression",Concat(["RelationalExpression";"Ge";"ShiftExpression"]));
   ("UsingGtRelationalExpression",Concat(["RelationalExpression";"Gt";"ShiftExpression"]));
   ("UsingIncrUnaryExpression",Concat(["Incr";"UnaryExpression"]));
   ("UsingLeRelationalExpression",Concat(["RelationalExpression";"Le";"ShiftExpression"]));
   ("UsingLsShiftExpression",Concat(["ShiftExpression";"Ls";"AdditiveExpression"]));
   ("UsingLtRelationalExpression",Concat(["RelationalExpression";"Lt";"ShiftExpression"]));
   ("UsingMinusAdditiveExpression",Concat(["AdditiveExpression";"Minus";"MultiplicativeExpression"]));
   ("UsingMinusUnaryExpression",Concat(["Minus";"UnaryExpression"]));
   ("UsingModMultiplicativeExpression",Concat(["MultiplicativeExpression";"Mod";"UnaryExpression"]));
   ("UsingNotUnaryExpressionNotPlusMinus",Concat(["Not";"UnaryExpression"]));
   ("UsingPlusAdditiveExpression",Concat(["AdditiveExpression";"Plus";"MultiplicativeExpression"]));
   ("UsingPlusUnaryExpression",Concat(["Plus";"UnaryExpression"]));
   ("UsingSrsShiftExpression",Concat(["ShiftExpression";"Srs";"AdditiveExpression"]));
   ("UsingSuperWildcardBounds",Concat(["Super";"ReferenceType"]));
   ("UsingThisPrimaryNoNewArray",Concat(["TypeName";"MolecularDot_This"]));
   ("UsingThreeDotsRecordComponent",Concat(["StarredRecordComponentModifier";"UnannType";"StarredAnnotation";"MolecularDot_Dot_Dot_Identifier"]));
   ("UsingTimesMultiplicativeExpression",Concat(["MultiplicativeExpression";"Times";"UnaryExpression"]));
   ("UsingUrsShiftExpression",Concat(["ShiftExpression";"Urs";"AdditiveExpression"]));
   ("UsualClassType",Concat(["PackageName";"Dot";"StarredAnnotation";"TypeIdentifier";"OptionalTypeArguments"]));
   ("UsualParameter",Concat(["StarredVariableModifier";"UnannType";"StarredAnnotation";"MolecularDot_Dot_Dot_Identifier"]));
   ("Var",Molecular([VAR_T]));
   ("VariableAccess",Disjunction(["ExpressionName";"FieldAccess"]));
   ("VariableDeclaratorPrecededByComma",Concat(["MolecularCm_Identifier";"OptionalDims";"OptionalEqualsVariableInitializer"]));
   ("VariableInitializer",Disjunction(["Expression";"ArrayInitializer"]));
   ("VariableInitializerList",Concat(["VariableInitializer";"StarredVariableInitializerPrecededByComma"]));
   ("VariableInitializerPrecededByComma",Concat(["Cm";"VariableInitializer"]));
   ("VariableModifier",Disjunction(["Annotation";"Final"]));
   ("Void",Molecular([VOID_T]));
   ("Volatile",Molecular([VOLATILE_T]));
   ("WhileStatement",Concat(["MolecularWhile_Lp";"Expression";"Rp";"Statement"]));
   ("WhileStatementNoShortIf",Concat(["MolecularWhile_Lp";"Expression";"Rp";"StatementNoShortIf"]));
   ("Wildcard",Concat(["StarredAnnotation";"Cond";"OptionalWildcardBounds"]));
   ("WildcardBounds",Disjunction(["UsingExtendsWildcardBounds";"UsingSuperWildcardBounds"]));
   ("WithColonAssertStatement",Concat(["Assert";"Expression";"Colon";"Expression";"Sm"]));
   ("WithEqEqEqualityExpression",Concat(["EqualityExpression";"StrongEq";"RelationalExpression"]));
   ("WithExclamationEqEqualityExpression",Concat(["EqualityExpression";"ExclamationEq";"RelationalExpression"]));
   ("WithoutColonAssertStatement",Concat(["Assert";"Expression";"Sm"]));
   ("Xor",Molecular([XOR_T]));
   ("Yield",Molecular([YIELD_T]));
   ("YieldStatement",Concat(["Yield";"Expression";"Sm"]));

]);;


(* Java grammar ends here *)

let mods_for_import_declaration = [
   (Lm_expand_disjunction(1,2));

(Lm_expand_synonym(1,2));
(Lm_expand_concat(2,2));
(Lm_expand_synonym(2,5));
(Lm_implode_molecule(2,(4,5)));

(Lm_reunite_star(1,(2,1)));
(Lm_explode_molecule(2,3));
(Lm_explode_molecule(2,1));

(Lm_implode_molecule(2,(4,5)));
(Lm_detect_optional(1,(3,1)));

(Lm_expand_disjunction(3,2));
(Lm_expand_disjunction(2,2));
(Lm_expand_concat(5,2));
(Lm_expand_concat(3,2));
(Lm_expand_synonym(5,5));
(Lm_expand_synonym(4,2));
(Lm_expand_synonym(3,5));
(Lm_expand_synonym(2,2));
(Lm_implode_molecule(3,(4,5)));
(Lm_reunite_star(2,(2,1)));
(Lm_explode_molecule(2,4));
(Lm_explode_molecule(3,3));
(Lm_explode_molecule(4,6));
(Lm_implode_molecule(4,(4,5)));
(Lm_reunite_star(3,(2,3)));
(Lm_reunite_disjunction((2,3),5));
(Lm_explode_molecule(2,1));
(Lm_implode_concat(1,(2,4)));
(Lm_implode_molecule(2,(2,3)));
(Lm_implode_concat(2,(2,5)));
(Lm_reunite_disjunction((1,2),2));
] ;;


let modifications_to_original_java_grammar = 
    [
      (* The following four actions remove left recursions and are fully equivalent to the original *)
      
      Flatten_triangle("AmbiguousName");
      Flatten_triangle("ModuleName");
      Flatten_triangle("PackageName");
      Flatten_triangle("PackageOrTypeName");
      Flatten_tetris1("ExpressionName");
      Remove_productions( [
      "AmbiguousName"; "CompoundAmbiguousName";  "ModuleName";
      "PackageName"; "PackageOrTypeName"]);
      (* Simplify the production rule for the import declaration*)
      Register_with_standardized_name (Optional("Static")) ;
      Register_with_standardized_name (Molecular([DOT_T;TIMES_T])) ;
      Register_with_standardized_name (Optional("MolecularDot_Times"));
      Register_with_standardized_name (Molecular([STATIC_T;IDENTIFIER_T]));
      Create_production("IdOrWildcard",Disjunction(["Identifier";"Times"]));
      Create_production("NonstaticImportedContent",Concat(["Identifier"; "StarredMolecularDot_Identifier";"OptionalMolecularDot_Times"]));
      Create_production("StaticImportedContent",Concat(["MolecularStatic_Identifier"; "StarredMolecularDot_Identifier"; "Dot";"IdOrWildcard"]));
      Create_production("ImportedContent",Disjunction(["NonstaticImportedContent";"StaticImportedContent"]));

      Local("ImportDeclaration",mods_for_import_declaration);
      Remove_productions( ["MolecularDot_Identifier_Sm"; "MolecularDot_Times_Sm";
      "MolecularImport_Identifier"; "MolecularImport_Static";
      "MolecularImport_Static_Identifier"; "SingleStaticImportDeclaration";
      "SingleTypeImportDeclaration"; "StaticImportOnDemandDeclaration";
      "TypeImportOnDemandDeclaration"]);
      (* Simplify the production rule for the class body declaration*)
      Expand_in_disjunction("ClassMemberDeclaration","ClassBodyDeclaration");
      Expand_in_synonym("Block","InstanceInitializer");
      Expand_in_disjunction("ClassDeclaration","ClassBodyDeclaration");
      Expand_in_disjunction("InterfaceDeclaration","ClassBodyDeclaration");
      Expand_in_disjunction("Annotation","ConstructorModifier");
      Expand_in_disjunction("Annotation","InterfaceModifier");
      Expand_in_disjunction("Annotation","MethodModifier");
      Collapse_synonym_locally("UnannInterfaceType","UnannClassOrInterfaceType");
      Collapse_synonym_globally("UnannClassOrInterfaceType");
      Expand_in_disjunction("UnannPrimitiveType","UnannType");
      Expand_in_disjunction("UnannReferenceType","UnannType");
      Collapse_synonym_locally("UnannTypeVariable","UnannType");
      Expand_in_disjunction("NumericType","UnannType");
      Expand_in_disjunction("UnannClassType","UnannType");
      Expand_in_disjunction("UnannArrayType","UnannType");
      Expand_in_disjunction("FloatingPointType","UnannType");
      Expand_in_disjunction("IntegralType","UnannType");
     (*
       Creating a fully equivalent production for UnannClassType, begin
     *)
      Create_production("MediumUnannClassType",Concat(["Identifier"; "StarredMolecularDot_Identifier"]));
      Create_production("BasicUnannClassType",Disjunction(["ShortUnannClassType"; "MediumUnannClassType"]));
      Create_production("UnannClassTypeExtender",Concat(["Dot";"StarredAnnotation"; "TypeIdentifier"; "OptionalTypeArguments"]));
      Create_production("StarredUnannClassTypeExtender",Star("UnannClassTypeExtender"));
      Set_production("UnannClassType",Concat(["BasicUnannClassType";"StarredUnannClassTypeExtender"]));
      (*
       Creating a fully equivalent production for UnannClassType, end
     *)
     (*
       Creating a fully equivalent production for TypeName, begin
     *)
     Set_production("TypeName",Concat(["Identifier";"StarredMolecularDot_Identifier"]));
     (*
       Creating a fully equivalent production for TypeName, end
     *)
      Remove_productions(["ClassMemberDeclaration"; "UnannArrayType"; "UnannInterfaceType";"UnannReferenceType";
      "Permits"; "Snail"; "CompoundTypeName"; "TypeName";
  "UnannClassType"
      ]);
      (* Introducting a new production, related to ShortUnannClassType*)
      Set_production("StrictShortUnannClassType",Concat(["Identifier";"Lt";"TypeArgument";"StarredTypeArgumentPrecededByComma";"Gt"]));
      Set_production("ShortUnannClassType",Disjunction(["Identifier";"StrictShortUnannClassType"]));
      Expand_in_disjunction("ShortUnannClassType","UnannType");
      Expand_in_disjunction("ShortUnannClassType","BasicUnannClassType");

      Expand_in_disjunction("NumericType","UnannPrimitiveType");
      Expand_in_disjunction("FloatingPointType","UnannPrimitiveType");
      Expand_in_disjunction("IntegralType","UnannPrimitiveType");

       (* Introducting a new production, related to MediumUnannClassType*)
      Set_production("StrictMediumUnannClassType",Concat(["Identifier";"Dot";"Identifier";"StarredMolecularDot_Identifier";]));
      Set_production("MediumUnannClassType",Disjunction(["Identifier";"StrictMediumUnannClassType"]));
      Expand_in_disjunction("MediumUnannClassType","BasicUnannClassType");
      Remove_productions(["MediumUnannClassType"; "ShortUnannClassType"]);
      Rename("StrictMediumUnannClassType","MediumUnannClassType");
      Rename("StrictShortUnannClassType","MediumShortClassType");
      
      Remove_productions(["ExceptionType"; "ExceptionTypePrecededByComma"; "Sends";
      "StarredExceptionTypePrecededByComma"]);
    ] ;;

let java_grammar = 
   original_java_grammar  ;;
  (*
    Jvag_grammar.modify original_java_grammar 
     modifications_to_original_java_grammar ;;
   *)
 end ;;


let java_grammar = Private.java_grammar ;;
